// Gerenciado pelo Painel de Molduras Lions v64
window.PUBLICACAO = {
  "versao": "1784917485034-qjoh9as",
  "atualizadoEm": "2026-07-24T18:24:45.034Z",
  "descricao": "Adiciona moldura Secretária de Clube"
};

window.CONFIGURACOES = {
  "duracaoNovo": {
    "valor": 3,
    "unidade": "dias"
  },
  "duracaoAtualizada": {
    "valor": 3,
    "unidade": "dias"
  },
  "mostrarNovo": true,
  "mostrarAtualizada": true,
  "cores": {
    "novo": "#2f9e72",
    "atualizada": "#d99a16",
    "visivel": "#2d8fd5",
    "oculta": "#7b8794"
  },
  "lembrarCategorias": true,
  "mostrarContadorCategoria": true,
  "confirmarPublicacao": true,
  "confirmarDescarte": true,
  "excluirImagemPadrao": true
};

window.CATEGORIAS = [
  {
    "id": "ircd-26-27",
    "nome": "✨ Eventos",
    "ordem": 1,
    "ativo": true
  },
  {
    "id": "al-2026-2027",
    "nome": "🦁💛 AL 2026/2027",
    "ordem": 2,
    "ativo": true
  },
  {
    "id": "causas-globais",
    "nome": "🌎 Causas Globais",
    "ordem": 3,
    "ativo": true
  },
  {
    "id": "lions",
    "nome": "🦁 Lions",
    "ordem": 4,
    "ativo": true
  },
  {
    "id": "cargos",
    "nome": "💼 Cargos de Clube",
    "ordem": 5,
    "ativo": true
  },
  {
    "id": "lions-corumba-pantanal-distrito-lb-1",
    "nome": "🦁 Lions Clube Corumbá Pantanal - Distrito LB-1",
    "ordem": 6,
    "ativo": true
  }
];

window.MOLDURAS = [
  {
    "id": "nos-vamos-ircd",
    "nome": "Nós Vamos no I RCD AL26/27",
    "categoriaId": "ircd-26-27",
    "ordem": 1,
    "arquivo": "assets/molduras/nos-vamos-ircd.png",
    "ativo": true,
    "status": "atualizada",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T01:45:56.151Z",
    "statusAte": "2026-07-27T01:45:56.151Z"
  },
  {
    "id": "eu-vou-ircd",
    "nome": "Eu Vou no I RCD AL 26/27",
    "categoriaId": "ircd-26-27",
    "ordem": 2,
    "arquivo": "assets/molduras/eu-vou-ircd.png",
    "ativo": true,
    "status": "atualizada",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T01:45:56.151Z",
    "statusAte": "2026-07-27T01:45:56.151Z"
  },
  {
    "id": "novo-associado",
    "nome": "Novo Associado",
    "categoriaId": "cargos",
    "ordem": 5,
    "arquivo": "assets/molduras/novo-associado.png",
    "ativo": true,
    "status": "atualizada",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T02:12:25.837Z",
    "statusAte": "2026-07-27T02:12:25.837Z"
  },
  {
    "id": "presidente-de-clube",
    "nome": "Presidente de Clube",
    "categoriaId": "cargos",
    "ordem": 6,
    "arquivo": "assets/molduras/presidente-de-clube.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "primeiro-vice-presidente-de-clube",
    "nome": "Primeiro Vice Presidente de Clube",
    "categoriaId": "cargos",
    "ordem": 7,
    "arquivo": "assets/molduras/primeiro-vice-presidente-de-clube.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "secretario-de-clube",
    "nome": "Secretario de Clube",
    "categoriaId": "cargos",
    "ordem": 9,
    "arquivo": "assets/molduras/secretario-de-clube.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "segundo-vice-presidente-de-clube",
    "nome": "Segundo Vice Presidente de Clube",
    "categoriaId": "cargos",
    "ordem": 8,
    "arquivo": "assets/molduras/segundo-vice-presidente-de-clube.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "assessor-de-marketing",
    "nome": "Assessor de Marketing",
    "categoriaId": "cargos",
    "ordem": 1,
    "arquivo": "assets/molduras/assessor-de-marketing.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "assessor-de-servicos-do-clube",
    "nome": "Assessor de Serviços do Clube",
    "categoriaId": "cargos",
    "ordem": 2,
    "arquivo": "assets/molduras/assessor-de-servicos-do-clube.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "assessor-de-socios-do-clube",
    "nome": "Assessor de Sócios do Clube",
    "categoriaId": "cargos",
    "ordem": 3,
    "arquivo": "assets/molduras/assessor-de-socios-do-clube.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "diretor-de-clube",
    "nome": "Diretor de Clube",
    "categoriaId": "cargos",
    "ordem": 4,
    "arquivo": "assets/molduras/diretor-de-clube.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "tesoureiro-de-clube",
    "nome": "Tesoureiro de Clube",
    "categoriaId": "cargos",
    "ordem": 10,
    "arquivo": "assets/molduras/tesoureiro-de-clube.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "socorro-a-catastrofes",
    "nome": "Socorro a Catástrofes",
    "categoriaId": "causas-globais",
    "ordem": 7,
    "arquivo": "assets/molduras/socorro-a-catastrofes.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "cancer-infantil",
    "nome": "Câncer Infantil",
    "categoriaId": "causas-globais",
    "ordem": 1,
    "arquivo": "assets/molduras/cancer-infantil.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "diabetes",
    "nome": "Diabetes",
    "categoriaId": "causas-globais",
    "ordem": 2,
    "arquivo": "assets/molduras/diabetes.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "esforcos-humanitarios",
    "nome": "Esforços Humanitários",
    "categoriaId": "causas-globais",
    "ordem": 3,
    "arquivo": "assets/molduras/esforcos-humanitarios.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "fome",
    "nome": "Fome",
    "categoriaId": "causas-globais",
    "ordem": 4,
    "arquivo": "assets/molduras/fome.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "visao",
    "nome": "Visão",
    "categoriaId": "causas-globais",
    "ordem": 8,
    "arquivo": "assets/molduras/visao.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "juventude",
    "nome": "Juventude",
    "categoriaId": "causas-globais",
    "ordem": 5,
    "arquivo": "assets/molduras/juventude.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "meio-ambiente",
    "nome": "Meio Ambiente",
    "categoriaId": "causas-globais",
    "ordem": 6,
    "arquivo": "assets/molduras/meio-ambiente.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "feliz-aniversario",
    "nome": "Feliz Aniversário",
    "categoriaId": "lions",
    "ordem": 2,
    "arquivo": "assets/molduras/feliz-aniversario.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "orgulho-de-ser-leao",
    "nome": "Orgulho de ser Leão",
    "categoriaId": "lions",
    "ordem": 7,
    "arquivo": "assets/molduras/orgulho-de-ser-leao.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T01:41:57.972Z",
    "statusAte": "2026-07-27T01:41:57.972Z"
  },
  {
    "id": "dia-d",
    "nome": "Dia D",
    "categoriaId": "lions",
    "ordem": 1,
    "arquivo": "assets/molduras/dia-d.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T01:41:57.972Z",
    "statusAte": "2026-07-27T01:41:57.972Z"
  },
  {
    "id": "gat",
    "nome": "GAT",
    "categoriaId": "lions",
    "ordem": 3,
    "arquivo": "assets/molduras/gat.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "get",
    "nome": "GET",
    "categoriaId": "lions",
    "ordem": 4,
    "arquivo": "assets/molduras/get.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "glt",
    "nome": "GLT",
    "categoriaId": "lions",
    "ordem": 5,
    "arquivo": "assets/molduras/glt.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "gmt",
    "nome": "GMT",
    "categoriaId": "lions",
    "ordem": 6,
    "arquivo": "assets/molduras/gmt.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false,
    "statusDesde": "",
    "statusAte": ""
  },
  {
    "id": "eu-vou-porco-no-rolete",
    "nome": "Eu Vou no Porco no Rolete",
    "categoriaId": "ircd-26-27",
    "ordem": 3,
    "arquivo": "assets/molduras/eu-vou-porco-no-rolete.png",
    "ativo": true,
    "status": "atualizada",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T01:45:56.152Z",
    "statusAte": "2026-07-27T01:45:56.152Z"
  },
  {
    "id": "nos-vamos-porco-no-rolete",
    "nome": "Nós Vamos no Porco no Rolete",
    "categoriaId": "ircd-26-27",
    "ordem": 4,
    "arquivo": "assets/molduras/nos-vamos-porco-no-rolete.png",
    "ativo": true,
    "status": "atualizada",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T01:45:56.152Z",
    "statusAte": "2026-07-27T01:45:56.152Z"
  },
  {
    "id": "eu-vou-no-treinamento",
    "nome": "Eu Vou no Treinamento",
    "categoriaId": "ircd-26-27",
    "ordem": 5,
    "arquivo": "assets/molduras/eu-vou-no-treinamento.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T01:41:30.857Z",
    "statusAte": "2026-07-27T01:41:30.857Z"
  },
  {
    "id": "nos-vamos-no-treinamento",
    "nome": "Nós Vamos no Treinamento",
    "categoriaId": "ircd-26-27",
    "ordem": 6,
    "arquivo": "assets/molduras/nos-vamos-no-treinamento.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T01:50:25.579Z",
    "statusAte": "2026-07-27T01:50:25.579Z"
  },
  {
    "id": "nos-vamos-ministrar-o-treinamento",
    "nome": "Nós Vamos Ministrar o Treinamento",
    "categoriaId": "ircd-26-27",
    "ordem": 8,
    "arquivo": "assets/molduras/nos-vamos-ministrar-o-treinamento.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T01:50:27.968Z",
    "statusAte": "2026-07-27T01:50:27.968Z"
  },
  {
    "id": "eu-vou-ministrar-o-treinamento",
    "nome": "Eu Vou Ministrar o Treinamento",
    "categoriaId": "ircd-26-27",
    "ordem": 7,
    "arquivo": "assets/molduras/eu-vou-ministrar-o-treinamento.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T01:50:30.696Z",
    "statusAte": "2026-07-27T01:50:30.696Z"
  },
  {
    "id": "assessor-de-marketing-de-clube-al-26-27",
    "nome": "Assessor de Marketing de Clube AL 26/27",
    "categoriaId": "al-2026-2027",
    "ordem": 3,
    "arquivo": "assets/molduras/assessor-de-marketing-de-clube-al-26-27.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T14:29:09.769Z",
    "statusAte": "2026-07-27T14:29:09.769Z"
  },
  {
    "id": "diretor-social-de-clube-al-26-27",
    "nome": "Diretor Social de Clube AL 26/27",
    "categoriaId": "al-2026-2027",
    "ordem": 5,
    "arquivo": "assets/molduras/diretor-social-de-clube-al-26-27.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T14:29:12.404Z",
    "statusAte": "2026-07-27T14:29:12.404Z"
  },
  {
    "id": "assessor-de-servicos-de-clube-al-26-27",
    "nome": "Assessor de Serviços de Clube AL 26/27",
    "categoriaId": "al-2026-2027",
    "ordem": 4,
    "arquivo": "assets/molduras/assessor-de-servicos-de-clube-al-26-27.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T14:29:15.258Z",
    "statusAte": "2026-07-27T14:29:15.258Z"
  },
  {
    "id": "assessor-de-associados-de-clube-al-26-27",
    "nome": "Assessor de Associados de Clube AL 26/27",
    "categoriaId": "al-2026-2027",
    "ordem": 2,
    "arquivo": "assets/molduras/assessor-de-associados-de-clube-al-26-27.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T14:29:18.653Z",
    "statusAte": "2026-07-27T14:29:18.653Z"
  },
  {
    "id": "tesoureiro-de-clube-al-26-27",
    "nome": "Tesoureiro de Clube AL 26/27",
    "categoriaId": "al-2026-2027",
    "ordem": 12,
    "arquivo": "assets/molduras/tesoureiro-de-clube-al-26-27.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T14:29:21.577Z",
    "statusAte": "2026-07-27T14:29:21.577Z"
  },
  {
    "id": "tesoureira-de-clube-al-26-27",
    "nome": "Tesoureira de Clube AL 26/27",
    "categoriaId": "al-2026-2027",
    "ordem": 11,
    "arquivo": "assets/molduras/tesoureira-de-clube-al-26-27.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T14:29:25.262Z",
    "statusAte": "2026-07-27T14:29:25.262Z"
  },
  {
    "id": "secretario-de-clube-al-26-27",
    "nome": "Secretário de Clube AL 26/27",
    "categoriaId": "al-2026-2027",
    "ordem": 10,
    "arquivo": "assets/molduras/secretario-de-clube-al-26-27.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T14:29:28.138Z",
    "statusAte": "2026-07-27T14:29:28.138Z"
  },
  {
    "id": "secretaria-de-clube-al-26-27",
    "nome": "Secretária de Clube AL 26/27",
    "categoriaId": "al-2026-2027",
    "ordem": 9,
    "arquivo": "assets/molduras/secretaria-de-clube-al-26-27.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T14:29:31.254Z",
    "statusAte": "2026-07-27T14:29:31.254Z"
  },
  {
    "id": "ex-presidente-imediato-de-clube-al-26-27",
    "nome": "Ex Presidente Imediato de Clube AL 26/27",
    "categoriaId": "al-2026-2027",
    "ordem": 6,
    "arquivo": "assets/molduras/ex-presidente-imediato-de-clube-al-26-27.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T14:29:34.009Z",
    "statusAte": "2026-07-27T14:29:34.009Z"
  },
  {
    "id": "vice-presidente-de-clube-al-26-27",
    "nome": "Vice Presidente de Clube AL 26/27",
    "categoriaId": "al-2026-2027",
    "ordem": 8,
    "arquivo": "assets/molduras/vice-presidente-de-clube-al-26-27.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T14:29:36.939Z",
    "statusAte": "2026-07-27T14:29:36.939Z"
  },
  {
    "id": "presidente-de-clube-al-26-27",
    "nome": "Presidente de Clube AL 26/27",
    "categoriaId": "al-2026-2027",
    "ordem": 7,
    "arquivo": "assets/molduras/presidente-de-clube-al-26-27.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T14:29:39.956Z",
    "statusAte": "2026-07-27T14:29:39.956Z"
  },
  {
    "id": "administrador-de-clube-al-26-27",
    "nome": "Administrador de Clube AL 26/27",
    "categoriaId": "al-2026-2027",
    "ordem": 1,
    "arquivo": "assets/molduras/administrador-de-clube-al-26-27.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T17:00:06.404Z",
    "statusAte": "2026-07-27T17:00:06.405Z"
  },
  {
    "id": "companheiro-de-clube-lions-corumba-pantanal",
    "nome": "Companheiro de Clube",
    "categoriaId": "lions-corumba-pantanal-distrito-lb-1",
    "ordem": 5,
    "arquivo": "assets/molduras/companheiro-de-clube-lions-corumba-pantanal.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T17:48:52.121Z",
    "statusAte": "2026-07-27T17:48:52.121Z"
  },
  {
    "id": "presidente-de-clube-lions-corumba-pantanal",
    "nome": "Presidente de Clube",
    "categoriaId": "lions-corumba-pantanal-distrito-lb-1",
    "ordem": 8,
    "arquivo": "assets/molduras/presidente-de-clube-lions-corumba-pantanal.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T17:48:58.102Z",
    "statusAte": "2026-07-27T17:48:58.102Z"
  },
  {
    "id": "vice-presidente-de-clube-lions-corumba-pantanal",
    "nome": "Vice Presidente de Clube",
    "categoriaId": "lions-corumba-pantanal-distrito-lb-1",
    "ordem": 9,
    "arquivo": "assets/molduras/vice-presidente-de-clube-lions-corumba-pantanal.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T17:49:00.921Z",
    "statusAte": "2026-07-27T17:49:00.921Z"
  },
  {
    "id": "ex-presidente-imediato-de-clube-lions-corumba-pantanal",
    "nome": "Ex Presidente Imediato de Clube",
    "categoriaId": "lions-corumba-pantanal-distrito-lb-1",
    "ordem": 7,
    "arquivo": "assets/molduras/ex-presidente-imediato-de-clube-lions-corumba-pantanal.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T17:49:03.785Z",
    "statusAte": "2026-07-27T17:49:03.785Z"
  },
  {
    "id": "secretaria-de-clube-lions-corumba-pantanal",
    "nome": "Secretária de Clube",
    "categoriaId": "lions-corumba-pantanal-distrito-lb-1",
    "ordem": 10,
    "arquivo": "assets/molduras/secretaria-de-clube-lions-corumba-pantanal.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T17:49:06.643Z",
    "statusAte": "2026-07-27T17:49:06.643Z"
  },
  {
    "id": "tesoureira-de-clube-lions-corumba-pantanal",
    "nome": "Tesoureira de Clube",
    "categoriaId": "lions-corumba-pantanal-distrito-lb-1",
    "ordem": 11,
    "arquivo": "assets/molduras/tesoureira-de-clube-lions-corumba-pantanal.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T17:49:09.495Z",
    "statusAte": "2026-07-27T17:49:09.495Z"
  },
  {
    "id": "assessor-de-associados-de-clube-lions-corumba-pantanal",
    "nome": "Assessor de Associados de Clube",
    "categoriaId": "lions-corumba-pantanal-distrito-lb-1",
    "ordem": 2,
    "arquivo": "assets/molduras/assessor-de-associados-de-clube-lions-corumba-pantanal.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T17:49:12.150Z",
    "statusAte": "2026-07-27T17:49:12.150Z"
  },
  {
    "id": "assessor-de-servicos-de-clube-lions-corumba-pantanal",
    "nome": "Assessor de Serviços de Clube",
    "categoriaId": "lions-corumba-pantanal-distrito-lb-1",
    "ordem": 4,
    "arquivo": "assets/molduras/assessor-de-servicos-de-clube-lions-corumba-pantanal.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T17:49:15.282Z",
    "statusAte": "2026-07-27T17:49:15.282Z"
  },
  {
    "id": "diretor-social-de-clube-lions-corumba-pantanal",
    "nome": "Diretor Social de Clube",
    "categoriaId": "lions-corumba-pantanal-distrito-lb-1",
    "ordem": 6,
    "arquivo": "assets/molduras/diretor-social-de-clube-lions-corumba-pantanal.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T17:49:18.012Z",
    "statusAte": "2026-07-27T17:49:18.012Z"
  },
  {
    "id": "assessor-de-marketing-de-clube-lions-corumba-pantanal",
    "nome": "Assessor de Marketing de Clube",
    "categoriaId": "lions-corumba-pantanal-distrito-lb-1",
    "ordem": 3,
    "arquivo": "assets/molduras/assessor-de-marketing-de-clube-lions-corumba-pantanal.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T17:49:21.259Z",
    "statusAte": "2026-07-27T17:49:21.259Z"
  },
  {
    "id": "administrador-de-clube-lions-corumba-pantanal",
    "nome": "Administrador de Clube",
    "categoriaId": "lions-corumba-pantanal-distrito-lb-1",
    "ordem": 1,
    "arquivo": "assets/molduras/administrador-de-clube-lions-corumba-pantanal.png",
    "ativo": true,
    "status": "novo",
    "statusVisivel": true,
    "statusDesde": "2026-07-24T17:49:23.987Z",
    "statusAte": "2026-07-27T17:49:23.987Z"
  },
  {
    "id": "secretaria-de-clube",
    "nome": "Secretária de Clube",
    "categoriaId": "cargos",
    "ordem": 11,
    "arquivo": "assets/molduras/secretaria-de-clube.png",
    "ativo": true,
    "status": "normal",
    "statusVisivel": false
  }
];
